### ISSUE TITLE
Endpoints da WP-JSON para o App

### ISSUE THREAD

**Issue by mateuswetah** [medialab-ufg/rhs-app#17]
Criar ou alterar endpoints customizados do plugin WP-JSON para atender às necessidades do app.

Criar:
- /wp/v2/votes/ (GET e POST)
-- autor do voto
-- post que recebeu o voto
-- timestamp?

Alterar:
- /wp/v2/posts/ (GET)
-- adicionar atributo votes (array de vote)
-- analisar se é possível ter o atributo shares
-- adicionar atributo followers (array de users)

Alterar:
- /wp/v2/users/ (GET)
-- adicionar atributo votes (array de vote) (ou não, o mesmo pode ser atingido filtrando GET votes por user...)
-- analisar se é possível ter o atributo shares
-- adicionar os atributos de descrição (atualmente só existe um description): Informações Pessoais, Sobre e Interesses...
-- adicionar atributo followers (array de users)
-- adicionar array de posts seguidos
-- adicionar array de users seguidos

**Comment by leogermani** [comment]
Feito endpoint para votar 

`POST /rhs/v1/votes/{id_post}`

## Adicionado no retorno de usuários:

* `followers` - usuários que seguem ele/ela
* `follows` - usuários que ele/ela segue
* `total_votes` - total de votos recebidos
* `formation`
* `interst`
* `state`
* `city`
* `links`
* e no caso de a requisição vir de um usuário logado, para o usuário dele também adicionamos:
* `posts_followed` - posts que ele segue

## Adicionado no retorno de posts:

* `total_votes`
* `comment_count`
* `total_shares`
