### ISSUE TITLE
achar outro plugin de google analytics com mais opções grátis

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/rhs-app#41]

**Comment by r-guimaraes** [comment]
Sei que já olharam essa questão.

Acharam algum plugin que se adequa melhor ao RHS?

**Comment by r-guimaraes** [comment]
Demanda: separar estatísticas de usuários logados/não-logados, e também identificar estatísticas de usuários (username, email,etc)

**Comment by mateuswetah** [comment]
Podemos fechar esse Issue? Me parece relacionado à rede como um todo...
