### ISSUE TITLE
Revisar votos no app

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/rhs-app#65]
Consegui votar inúmeras vezes no mesmo post através do App (versão para iOS).

Ao votar pelo app, o botão deveria ser desabilitado, assim como no site.

Além disso, vamos verificar se há a checagem por parte da API se aquele user já votou naquele post

**Comment by MarianaSalles** [comment]
ficou meio urgente isso. seria legal pegar logo. tanto no IOS como no android conseguir votar varias vezes. ;-)
