### ISSUE TITLE
Confirmar e-mail no formulário de cadastro

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/rhs-app#72]
Acrescentar campo para usuário confirmar e-mail de cadastro, evitando que envie informações digitadas incorretamente sem perceber

**Comment by r-guimaraes** [comment]
feito

**Comment by MarianaSalles** [comment]
ficou muito bom. resolveu. a mudança do titulo tb. faz mais sentido.;-) manda ver!
